version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: ${{secrets.INTERVAL}}
      time: ${{secrets.TIME}}
      timezone: ${{secrets.TIMEZONE}}
    labels:
      - ${{secrets.LABELS}}
    reviewers:
      - "jun-okb-115"
    commit-message:
      prefix: "dependabot: "
